### ISSUE TITLE
MessageBox disappears

### ISSUE THREAD

**Issue by satpal123** [OpenByteDev/ModernWpf.MessageBox#3]
Sometimes when the application is minimised, the Messagebox just doesnt show up in the end.

My method is an async and I use the following code when the process finishes, then displays the message

``` 
Application.Current.Dispatcher.Invoke(delegate
            {
                MessageBox.Show(resultmessage, resulttitle, MessageBoxButton.OK, MessageBoxImage.Warning);
            });
```

**Comment by OpenByteDev** [comment]
Does it not show up (as descripted in your text) or does it disappear after showing (like in the title)?

**Comment by satpal123** [comment]
It does show up most of the time but sometimes when my application is minimised/not in focus, then it disappears.

My application controls only enables after I get a successful message and I press OK button on the message box. When it just doesn't appear, then the app controls don't get enabled. I then have to close and reopen the application. 

I will try to repro it and let you know.

**Comment by satpal123** [comment]
I seem to have found the issue. 

In your code the `window.IsActive` which is mentioned in your MessageBox.cs , will look for the window if its active or else it will return null which in that case the MessageBox won't show up.

```
private static Window? GetActiveWindow() =>
            Application.Current.Windows.Cast<Window>().FirstOrDefault(window => window.IsActive);
```

And this the way I have done. In this case even if the application is minimized, the messagebox will show up. 
```
Application.Current.Dispatcher.Invoke(delegate
            {
                var owner = Application.Current.Windows.Cast<Window>().FirstOrDefault();

                MessageBox.Show(owner, resultmessage, resulttitle, MessageBoxButton.OK, MessageBoxImage.Information);
            });
```

I don't think this is a issue but atleast you have given the ability to provide the Window? owner parameter 👍
